//! `Anubis.lock` — exact version + content hash pins for every dependency.

use serde::{Deserialize, Serialize};
use std::path::Path;

pub const LOCK_FILENAME: &str = "Anubis.lock";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockFile {
    pub version: u32,
    #[serde(default)]
    pub package: Vec<LockedPackage>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    /// `registry` | `path` | `git`
    pub source: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub git: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rev: Option<String>,
    /// Optional registry base URL/path used to fetch this package (`file://` or `https://`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub registry: Option<String>,
    /// Merkle root of package payload (src + Anubis.toml + sealed evidence).
    pub content_sha256: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub evidence_sha256: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signer_public_key: Option<String>,
}

impl LockFile {
    pub fn empty() -> Self {
        Self {
            version: 1,
            package: Vec::new(),
        }
    }

    pub fn parse(text: &str) -> Result<Self, String> {
        toml::from_str(text).map_err(|e| format!("ANUBIS_LOCK_STALE: parse error: {e}"))
    }

    pub fn load(path: &Path) -> Result<Self, String> {
        let text = std::fs::read_to_string(path).map_err(|e| {
            format!(
                "ANUBIS_LOCK_MISSING: cannot read {}: {e}",
                path.display()
            )
        })?;
        Self::parse(&text)
    }

    pub fn to_toml_string(&self) -> Result<String, String> {
        let mut s = String::from(
            "# Anubis.lock — generated by `anubis package lock`. Pins version + content hash.\n",
        );
        s.push_str(
            &toml::to_string_pretty(self).map_err(|e| format!("ANUBIS_LOCK_STALE: {e}"))?,
        );
        Ok(s)
    }

    pub fn save(&self, path: &Path) -> Result<(), String> {
        let text = self.to_toml_string()?;
        std::fs::write(path, text).map_err(|e| e.to_string())
    }

    pub fn get(&self, name: &str) -> Option<&LockedPackage> {
        self.package.iter().find(|p| p.name == name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip() {
        let mut lf = LockFile::empty();
        lf.package.push(LockedPackage {
            name: "math".into(),
            version: "1.0.0".into(),
            source: "path".into(),
            path: Some("../math".into()),
            git: None,
            rev: None,
            registry: None,
            content_sha256: "abc".into(),
            evidence_sha256: Some("def".into()),
            signer_public_key: Some("pk".into()),
        });
        let t = lf.to_toml_string().unwrap();
        let p = LockFile::parse(&t).unwrap();
        assert_eq!(p.package[0].name, "math");
        assert_eq!(p.package[0].content_sha256, "abc");
    }
}
